<?php
/**
 * Created by PhpStorm.
 * User: hiwin045
 * Date: 2018/7/17
 * Time: 11:20
 */

namespace app\index\controller;


use think\Controller;
use think\Session;

class CommonController extends Controller
{
    //登录状态监测
    protected function _initialize()
    {
//        parent::_initialize(); // TODO: Change the autogenerated stub
        $user=Session::has('user');
        if (!$user){
            //记住跳到登录前的最后的url 适合前台 后台有frame
            redirect('./login')->remember();
            $this->redirect('./login');
        }
    }

}